config/routes.rb
TryAgain::Application.routes.draw do
  match "find_by_zipcode", :to => "locations#find_by_zipcode"
  resources :locations

  root :to => 'locations#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"
  get "static_pages/contact"

      match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/home', to: 'static_pages#home'
  match '/', to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :zip_code, :lat, :lng


  acts_as_mappable
  before_create :more_infor

  private
  def more_infor
    geo = Geokit::Geocoders::MultiGeocoder.geocode self.address
    errors.add(:address, "Could not Geocode address") if !geo.success
    self.lat, self.lng, self.zip_code = geo.lat, geo.lng, geo.zip if geo.success
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#
class User < ActiveRecord::Base
  
  attr_accessible :name, :email, :password, :password_confirmation
  # callback method
  has_secure_password

  before_save { |user| user.email = email.downcase }
  # alter : before_save { email.downcase! }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
    format:     { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 3 }
  validates :password_confirmation, presence: true
  
  private 
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end
  def find_by_address
    addr = params[:address]
    @geo = Geokit::Geocoders::MultiGeocoder.geocode addr
    respond_to do |format|
      format.js
    end
  end

  def find_by_zipcode
    zip = params[:zip]
    distance = params[:distance]
    @locations= Location.geo_scope(:within => params[:distance], :origin => params[:zip])
    respond_to do |format|
      format.js
    end
  end
  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to locations_url, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # lay thong tin user duoc submit
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # chung thuc thanh cong
      sign_in user # ghi vao cookies
      redirect_to user
      flash[:notice] = "Welcome back !"
      # Sign the user in and redirect to the user's show page.
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit,:update]
  before_filter :correct_user, only: [:edit, :update]
  
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
  end
  def create
    @user = User.new(params[:user])
    # equivalent to : 
    # @user = User.new(name: "Foo Bar", email: "foo@invalid",
    #password: "foo", password_confirmation: "bar")
    if @user.save #validated
      flash[:message] = "Sign Up successful! Welcome !"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(params[:user])
      # Handle a successful update.
      # kiem tra neu truong password = nil
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private
  
  def signed_in_user
    unless signed_in?
      redirect_to signin_url, notice: "Please sign in."
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # xu li dang nhap
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    # cookies is utility supplied by Rails
    self.current_user = user
    # Create current_user, 
    # accessible in both controllers and views, 
    # which will allow constructions such as
    # <%= current_user.name %> and
    # redirect_to current_user
  end
  # kiem tra da dang nhap hay chua
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  
  def current_user=(user)
    @current_user = user
  end
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  def current_user?(user)
    user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact", contact_path%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Try Again !</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>

    </div>
  </body>
 
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
    <% if @location.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>
          <ul>
            <% @location.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="actions">
      <strong>Address</strong>
      <%= f.text_field :address %>
      <strong>Zip</strong>
      <%= f.text_field :zip_code %>
      <%= f.submit %>
    </div>
<% end %>

app/views/locations/_search_result.html.erb
<table class="table">
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Zip</th>
  </tr>

  <% @locations.each do |location| %>
      <tr>
        <td> <%= location.address %></td>
        <td> <%= location.lat %></td>
        <td> <%= location.lng %></td>
        <td> <%= location.zip_code %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>





<% if false %>

<% if @geo.success %>
    <p>Street name : <%= @geo.street_name %> </p>
    <p>Street address : <%= @geo.street_address %> </p>
    <p>City : <%= @geo.city %> </p>
    <p>Latitude : <%= @geo.lat %> </p>
    <p>Longitude : <%= @geo.lng %> </p>
    <p>Country : <%= @geo.country %> </p>
    <p>Zip : <%= @geo.zip %> </p>
    <p>Success: <%= @geo.success %></p>
<% else %>
    <h5> Not found !</h5>
<% end %>
<% end %>



app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/find_by_address.js.erb
$('.result').html("<%= escape_javascript render('locations/search_result') %>");

app/views/locations/find_by_zipcode.js.erb
$('.result').html("<%= escape_javascript render('locations/search_result') %>");

app/views/locations/index.html.erb
<style>
    .scroll-table{
        height: 200px;
        overflow: auto;
        border: #333333;
    }
</style>
<%= link_to 'New Location', new_location_path, :class => 'btn btn-snall ' %>
<h1>Listing locations</h1>

<div class="scroll-table">
<table class="table">
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Zip</th>
  </tr>

  <% @locations.each do |location| %>
      <tr>
        <td> <%= location.address %></td>
        <td> <%= location.lat %></td>
        <td> <%= location.lng %></td>
        <td> <%= location.zip_code %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>
  </div>
 <script type="text/javascript">
    $(document).ready(function () {
        $('#find_by_zipcode_btn').on("click", function () {
            var url = "/find_by_zipcode?zip=" + $('#zipcode_field').val() + "&distance=" + $('#distance_field').val();
            $.get(url,function () {
            }).done(function () {
                        $("html, body").animate({ scrollTop: $(document).height() }, 1000);
                    });
        });
    });
</script>
<% if false %>
    <%= text_field_tag 'address', nil, placeholder: 'Enter address', size: 20, id: 'address_field' %>
    <%= button_tag 'Find by Address', :id => 'find_by_address_btn' %>
    <br/>
<% end %>
<br/>
<%= label_tag 'Zipcode'%>
<%= text_field_tag 'zipcode', 94105, placeholder: 'Enter zipcode', size: 20, id: 'zipcode_field', :style => "max-width: 100px;" %>
<%= label_tag 'Distance'%>
<%= number_field_tag 'distance', 5, placeholder: 'distance', size: 20, id: 'distance_field', :style => "max-width: 100px;" %>
<br />
<%= button_tag 'Find !', :id => 'find_by_zipcode_btn' %>
<hr/>
<h3> Result</h3>
<div class="result">
</div>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/shared/_error_messages.html.erb
<% # kiem tra xem co loi hay khong %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% # hien ra cac error %>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>

    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
  </head>
  <body>
    <h1>About Us</h1>
    <p>
      The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      is a project to make a book and screencasts to teach web development
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
      is the sample application for the tutorial.
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>
  </head>
  <body>
    <div class="center hero-unit">
      <h1>The Vault Project</h1>
      <h2>
        This is the home page edit !
      </h2>
      <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
      </div>
    </body>
  </html>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name , :placeHolder => "John Smith" %>

      <%= f.label :email %>
      <%= f.text_field :email, :placeHolder => "example@gmail.com"  %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
  
      </h1>
    </section>
  </aside>
</div>